### ISSUE TITLE
是否可以指明es依赖版本?

### ISSUE THREAD

**Issue by issakk** [xpc1024/easy-es#2]
老项目6.4.3发现低版本 缺少某些类
是否可以指明es依赖版本?
谢谢作者

**Comment by xpc1024** [comment]
你好,easy-es框架底层用的是es官方提供的RestHighLevelClient,版本是7.10.1,目前为了使用者方便,我在框架的Pom中并未指定依赖的RestHighLevelClient版本号由调用者自己提供,如果有版本依赖冲突,可以统一版本号,通过pom中的exclude标签移除或者版本号保持一致可解决,如果老项目版本号升级兼容困难,那我也无能为力了哈,这框架是今年刚开发的,所以用的技术栈和版本号都比较新. 你说的用6.4.3是版本冲突之后缺少的还是说统一了版本号之后缺少某些类? 如果是统一之后还缺少,那就是不行了,统一版本号之前出现缺少类你可以统一之后再试试,本框架依赖的所有包版本号可以参考这里:https://www.yuque.com/laohan-14b9d/foyrfa/gzax0p

**Comment by issakk** [comment]
谢谢作者耐心回答,确实是项目太老了.

**Comment by xpc1024** [comment]
不客气,感谢您关注easy-es,有问题或有需求可以及时提,我们会第一时间去处理
