### ISSUE TITLE
selectlist查询有问题，in查询条件没有构造进来

### ISSUE THREAD

**Issue by lifuxin11** [xpc1024/easy-es#3]
![image](https://user-images.githubusercontent.com/28385260/148337588-86f3abf3-00a9-4bb2-8af7-c2c43a89b2ec.png)
可以看到查询结果最多只能10条，且数据重复。

**Comment by lifuxin11** [comment]
![image](https://user-images.githubusercontent.com/28385260/148349889-3605f573-6709-4adc-9a1e-35a2461eaf14.png)

**Comment by xpc1024** [comment]
您好,非常感谢提出该Isuue,我在昨天下午第一时间确认了该问题,并定位到了原因,此问题本来是不存在的,是我在代码重构的时候不小心把一个重载的方法用错了,导致in的查询参数没有被正确封装进去.我昨天已经回复你了,但今天看并没有提交成功,很抱歉. 此问题已经被修复,感谢您对Easy-Es的关注,也敬请放心使用,有任何问题我会第一时间去解决,在修复之前,您仍可以使用原生查询,把Easy-Es当做是一个自动配置版的RestHighLevelClient去使用,不影响其它功能,修复后,您只需要改下版本号,升级Easy-Es即可解决.
此问题将会在0.9.4版本得到修复,届时,该版本会有一些新的特性和优化上线,预计在一周内完成上线. 最后再次感谢您对Easy-Es的支持.

**Comment by lifuxin11** [comment]
感谢提供该配置化插件， 极大简化开发工作，有幸在项目中使用，过程中一些问题和小优化建议将及时共享，同时因为es 默认 windowresultsize 的限制 ，每次查询命中的hit默认10条， 导致updatewrapper批量更新数据时一次只能更新10条，也请百忙之中测试下，建议在update前设置下query的 size应该能解决。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月7日(星期五) 上午10:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xpc1024/easy-es] selectlist查询有问题，in查询条件没有构造进来 (Issue #3)





 
您好,非常感谢提出该Isuue,我在昨天下午第一时间确认了该问题,并定位到了原因,此问题本来是不存在的,是我在代码重构的时候不小心把一个重载的方法用错了,导致in的查询参数没有被正确封装进去.我昨天已经回复你了,但今天看并没有提交成功,很抱歉. 此问题已经被修复,感谢您对Easy-Es的关注,也敬请放心使用,有任何问题我会第一时间去解决,在修复之前,您仍可以使用原生查询,把Easy-Es当做是一个自动配置版的RestHighLevelClient去使用,不影响其它功能,修复后,您只需要改下版本号,升级Easy-Es即可解决.
 此问题将会在0.9.4版本得到修复,届时,该版本会有一些新的特性和优化上线,预计在一周内完成上线. 最后再次感谢您对Easy-Es的支持.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xpc1024** [comment]
亲,已在2个工作日内修复您反馈的问题,另外还发布了一些新特性,0.9.4版本,目前已发布至maven中央仓库,您可以更新版本后使用了,验证后如果有得到解决麻烦关闭此issue,再次感谢~

**Comment by xpc1024** [comment]
仔细看了下,您反馈的windowresultsize也在这个版本规划的内容中一起上线了,非常巧的是,在您反馈之前我就观察到这个问题并正好在这个版本得到了解决,默认10条,目前调至1w条了,这是一个鱼与熊掌的问题,过于大的话,在一些极端场景下:比如数据量极大,用关键词去模糊匹配或范围查询时,一次查询会有上万条数据被查出来,如果不做限制,会把网卡和磁盘IO打满,严重影响系统性能,所以ES默认的windowresultsize为10条,RestHighLevelClient对单次请求的返回最大限制为100M,超过就会报错.但10条默认的限制会让用户误以为是程序bug,基于此种考虑,这边最终将单次返回的条数设置为1w条了,如需更大或者更小或者按需分配,用户可以在wrapper条件中自行指定size,如需精确的size大小,也可以通过我在mapper中提供的count方法进行获取.

本次更新功能点可参考这里0.9.4版本:https://www.yuque.com/laohan-14b9d/foyrfa/ixlx89

**Comment by 82Leonard** [comment]
上述问题如果确认被解决,还望能白忙之中抽空帮忙点下Close关闭此Issue,再次感谢!
